name: Update Migration Script Versions

description: Updates the names of the migration scripts with the next sequential version number

inputs:
  migration-script-path:
    description: The path to the migration scripts. Searching for the scripts is done recursively so pointing at a base directory with sub directories is ok.
    required: true
  max-version-gap:
    description: The maximum difference between valid versions and ones to update.
    required: true
    default: '100'

runs:
  using: "composite"
  steps:
    - name: Update migration scripts
      shell: pwsh
      run: ${{ github.action_path }}/src/update-migration-script-versions.ps1 -migrationPath "${{ inputs.migration-script-path }}" -maxVersionGap ${{ inputs.max-version-gap }}